# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=150)),
                ('secret', models.CharField(max_length=150)),
                ('server', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('ispublic', models.BooleanField()),
                ('isfriend', models.BooleanField()),
                ('isfamily', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Фото',
                'verbose_name': 'Фото',
            },
        ),
    ]
