# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_loader_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='farm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='photo',
            name='secret',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='photo',
            name='server',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
